// Script ponctuel : importe les 33 métiers du "Guide des Fiches Métiers à Madagascar"
// (Avenir assuré) dans la base. N'écrit que ces métiers (upsert par slug généré à partir du
// nom) ; les domaines et secteurs référencés doivent déjà exister (voir seed-domaines-guide.ts
// et seed-secteurs.ts).
// Usage : npx ts-node scripts/seed-guide-metiers.ts
import { PrismaClient } from '@prisma/client';
import { slugify } from '../src/common/utils/slugify';

const prisma = new PrismaClient();

interface MetierSeed {
  nom: string;
  domaine: string;
  secteur: string;
  sousDomaine: string;
  riasecCodes: string[];
  description: string;
  missions: string[];
  competences: string[];
  competencesComportementales: string[];
  seriesBacMadagascar: string[];
  formationsMadagascar: string[];
  niveauRequis: string;
  salaireMin: number;
  salaireMax: number;
  avantages: string;
}

const metiersData: MetierSeed[] = [
  {
    nom: 'Technicien Informatique & Réseaux',
    domaine: 'sciences-technologies', secteur: 'numerique-bpo-services-externalises',
    sousDomaine: 'Numérique, Informatique & Télécommunications',
    riasecCodes: ['R', 'C', 'I'],
    description: "Le technicien informatique installe, configure et maintient les équipements, réseaux et parcs informatiques des entreprises et administrations.",
    missions: [
      "Installer et configurer les postes de travail, imprimantes et équipements réseau (routeurs, switchs, Wi-Fi).",
      "Diagnostiquer et résoudre les pannes matérielles et logicielles signalées par les utilisateurs.",
      "Assurer la sécurité de base du réseau (antivirus, sauvegardes, mots de passe) et la maintenance préventive.",
      "Former les utilisateurs aux bonnes pratiques informatiques et tenir l'inventaire du parc.",
    ],
    competences: ["Sens pratique", "Patience face aux pannes récurrentes", "Bonne mémoire des procédures"],
    competencesComportementales: ["Capacité à diagnostiquer étape par étape", "Rigueur dans la documentation des interventions"],
    seriesBacMadagascar: ["S", "Technique Informatique", "OSE"],
    formationsMadagascar: [
      "Court & Qualifiant — Centres de formation informatique, certifications réseaux de base — 3 à 9 mois",
      "Supérieur Court (Bac+2) — BTS Maintenance Informatique et Réseaux — 2 ans",
      "Certifications — Cisco (CCNA), Microsoft, certifications constructeurs — en continu",
    ],
    niveauRequis: "Bac+2 (BTS)",
    salaireMin: 350000, salaireMax: 1300000,
    avantages: "Présent dans toutes les entreprises et administrations, base solide pour évoluer vers le développement ou l'administration système.",
  },
  {
    nom: 'Développeur Informatique / Programmeur',
    domaine: 'sciences-technologies', secteur: 'numerique-bpo-services-externalises',
    sousDomaine: 'Numérique, Informatique & Télécommunications',
    riasecCodes: ['I', 'R', 'C'],
    description: "Le développeur informatique conçoit, développe et maintient des logiciels, sites web ou applications mobiles pour des entreprises locales ou des clients internationaux.",
    missions: [
      "Analyser les besoins du client et concevoir l'architecture d'une application ou d'un site web.",
      "Écrire, tester et déboguer le code (langages web, mobile, bases de données).",
      "Participer à la conception de bases de données et à l'intégration d'API.",
      "Assurer la maintenance évolutive et corrective des applications livrées.",
    ],
    competences: ["Logique algorithmique", "Autonomie", "Capacité à travailler seul ou en équipe à distance"],
    competencesComportementales: ["Goût pour la résolution de problèmes", "Veille technologique permanente"],
    seriesBacMadagascar: ["S"],
    formationsMadagascar: [
      "Court & Qualifiant — Bootcamps et centres de formation courte en développement web — 3 à 9 mois",
      "Supérieur (Bac+3 à Bac+5) — ENI (Fianarantsoa), IT University, universités privées Informatique — 3 à 5 ans",
      "Certifications — Certifications en ligne (Google, Microsoft, AWS), plateformes freelance internationales — en continu",
    ],
    niveauRequis: "Bac+3 à Bac+5",
    salaireMin: 500000, salaireMax: 3000000,
    avantages: "Métier très demandé, possibilité de travailler à distance pour des clients étrangers (salaires en devises), secteur en forte croissance.",
  },
  {
    nom: 'Chargé(e) de Communication Digitale',
    domaine: 'arts-communication', secteur: 'numerique-bpo-services-externalises',
    sousDomaine: 'Communication, Marketing & Digital',
    riasecCodes: ['A', 'E', 'C'],
    description: "Le/la chargé(e) de communication digitale construit et anime l'image d'une entreprise, d'une marque ou d'une organisation sur les supports numériques.",
    missions: [
      "Élaborer le calendrier éditorial et créer du contenu pour les réseaux sociaux (textes, visuels, vidéos courtes).",
      "Gérer la relation avec la communauté en ligne et répondre aux messages/commentaires.",
      "Suivre les statistiques d'audience et ajuster la stratégie de communication en fonction des résultats.",
      "Coordonner des campagnes publicitaires en ligne et des partenariats avec des influenceurs locaux.",
    ],
    competences: ["Sens visuel", "Capacité à imaginer des contenus qui captent l'attention"],
    competencesComportementales: ["Lecture de statistiques (portée, engagement)", "Maîtrise des outils numériques"],
    seriesBacMadagascar: ["OSE", "L"],
    formationsMadagascar: [
      "Court & Qualifiant — Formations courtes en communication digitale, marketing des réseaux sociaux — 6 mois à 1 an",
      "Supérieur (Bac+3) — Département Communication (Université d'Antananarivo), écoles privées de communication/marketing — 3 ans (Licence)",
      "Auto-formation — Certifications marketing digital en ligne (Meta, Google) — en continu",
    ],
    niveauRequis: "Bac+3 (Licence)",
    salaireMin: 350000, salaireMax: 2000000,
    avantages: "Secteur en pleine expansion, possibilité de missions à distance pour des clients internationaux payés en devises.",
  },
  {
    nom: 'Journaliste',
    domaine: 'arts-communication', secteur: 'numerique-bpo-services-externalises',
    sousDomaine: 'Médias & Presse',
    riasecCodes: ['A', 'S', 'I'],
    description: "Le journaliste recherche, vérifie et diffuse l'information auprès du public, pour la presse écrite, la radio, la télévision ou les médias en ligne.",
    missions: [
      "Enquêter sur un sujet, recueillir des témoignages et vérifier les faits auprès de sources fiables.",
      "Rédiger des articles, reportages ou chroniques adaptés au support (presse écrite, radio, TV, web).",
      "Réaliser des interviews et couvrir des événements en direct.",
      "Respecter la déontologie journalistique et la loi sur la presse.",
    ],
    competences: ["Curiosité", "Esprit critique", "Aisance à l'oral et à l'écrit"],
    competencesComportementales: ["Bonne connaissance de l'actualité nationale et internationale"],
    seriesBacMadagascar: ["L", "S", "OSE"],
    formationsMadagascar: [
      "Court & Qualifiant — Formations courtes en journalisme (écoles privées, ateliers de presse) — 6 mois à 1 an",
      "Supérieur (Bac+3) — Département Communication et Journalisme (Université d'Antananarivo), écoles privées de journalisme — 3 ans (Licence)",
      "Perfectionnement — Ateliers de formation continue (fact-checking, investigation) — en continu",
    ],
    niveauRequis: "Bac+3 (Licence)",
    salaireMin: 300000, salaireMax: 1800000,
    avantages: "Rôle essentiel dans l'information du public, possibilité de collaborer avec des médias internationaux.",
  },
  {
    nom: 'Technicien en Énergie Solaire & Photovoltaïque',
    domaine: 'btp-energie-industrie', secteur: 'energies-renouvelables-btp-industrie-miniere',
    sousDomaine: 'Énergie renouvelable, BTP & Maintenance technique',
    riasecCodes: ['R', 'I', 'C'],
    description: "Le technicien solaire conçoit, installe et dépanne des systèmes photovoltaïques (panneaux solaires, régulateurs, onduleurs et parcs de batteries) pour des ménages, des entreprises ou des sites agricoles isolés.",
    missions: [
      "Faire le bilan de puissance électrique chez le client (calcul des besoins en kWh).",
      "Fixer les structures sur les toitures ou au sol en respectant l'orientation et l'inclinaison.",
      "Raccorder les câblages électriques, configurer les onduleurs hybrides et sécuriser l'installation (disjoncteurs, mise à la terre).",
      "Diagnostiquer les pannes de stockage (batteries au plomb ou lithium) et assurer la maintenance préventive.",
    ],
    competences: ["Pas de vertige (travail sur toiture)", "Habileté manuelle", "Rigueur face au risque d'électrocution"],
    competencesComportementales: ["Maîtrise des bases de l'électricité"],
    seriesBacMadagascar: ["S", "L", "OSE"],
    formationsMadagascar: [
      "Court & Qualifiant — Centres de formation professionnelle (CFP, CNFP, instituts de métiers de l'énergie) — 3 à 9 mois",
      "Supérieur Court (Bac+2/Bac+3) — IUT, IST (Génie Électrique), universités privées MESupReS en Énergies Renouvelables — 2 à 3 ans (DUT/Licence Pro)",
      "Auto-formation / Certifications — Formations de marques de matériel solaire + stages pratiques sur chantier — en continu",
    ],
    niveauRequis: "Bac+2 à Bac+3",
    salaireMin: 400000, salaireMax: 1800000,
    avantages: "Métier très demandé (délestages fréquents, zones rurales non raccordées à la JIRAMA), possibilité rapide de travailler à son propre compte, impact écologique direct.",
  },
  {
    nom: "Technicien de Chantier / Chef d'Équipe BTP",
    domaine: 'btp-energie-industrie', secteur: 'energies-renouvelables-btp-industrie-miniere',
    sousDomaine: 'Bâtiment & Travaux Publics',
    riasecCodes: ['R', 'C', 'S'],
    description: "Le technicien de chantier assure l'exécution technique quotidienne des travaux sur le terrain, encadre une équipe d'ouvriers et veille au respect des consignes techniques transmises par le conducteur de travaux.",
    missions: [
      "Mettre en œuvre les techniques de construction (maçonnerie, coffrage, ferraillage) sur le chantier.",
      "Encadrer une équipe d'ouvriers au quotidien et contrôler la qualité de leur travail.",
      "Effectuer les mesures et implantations nécessaires à partir des plans fournis.",
      "Veiller au respect des règles de sécurité sur le chantier et remonter les problèmes techniques.",
    ],
    competences: ["Sens pratique", "Expérience du geste technique du bâtiment", "Autorité de proximité"],
    competencesComportementales: ["Capacité à motiver une équipe d'ouvriers", "Faire respecter les consignes"],
    seriesBacMadagascar: ["S", "Technique Bâtiment"],
    formationsMadagascar: [
      "Court & Qualifiant — CFP Bâtiment, formation de chef d'équipe — 6 à 12 mois",
      "Supérieur Court (Bac+2) — BTS Bâtiment — 2 ans",
      "Certification — Formations sécurité chantier (HSE) — en continu",
    ],
    niveauRequis: "Bac+2 ou expérience terrain",
    salaireMin: 350000, salaireMax: 1000000,
    avantages: "Poste d'encadrement accessible avec l'expérience, forte demande dans le secteur du BTP en pleine expansion.",
  },
  {
    nom: 'Conducteur de Travaux BTP',
    domaine: 'btp-energie-industrie', secteur: 'energies-renouvelables-btp-industrie-miniere',
    sousDomaine: 'Bâtiment & Travaux Publics',
    riasecCodes: ['R', 'E', 'C'],
    description: "Le conducteur de travaux supervise l'exécution globale des chantiers de construction, de l'organisation du phasage jusqu'à la livraison de l'ouvrage, en pilotant plusieurs équipes et corps de métier.",
    missions: [
      "Lire les plans d'exécution et organiser le phasage complet des travaux sur le chantier.",
      "Encadrer les chefs d'équipe et coordonner les différents corps de métier (maçons, électriciens, plombiers).",
      "Contrôler la qualité des matériaux et la conformité des ouvrages avec le cahier des charges.",
      "Assurer le suivi administratif et budgétaire : métrés, bons de commande, rapports d'avancement.",
    ],
    competences: ["Sens de l'organisation", "Autorité naturelle", "Résistance physique et au soleil"],
    competencesComportementales: ["Capacité à gérer un budget de chantier complet", "Gestion de plusieurs équipes simultanément"],
    seriesBacMadagascar: ["S", "OSE"],
    formationsMadagascar: [
      "Supérieur (Bac+3 à Bac+5) — ESPA (Génie Civil), IST, écoles d'ingénieurs BTP — 3 à 5 ans",
      "Évolution interne — CFP Bâtiment + expérience terrain pour évoluer au poste — variable",
      "Certification — Formations sécurité chantier (HSE) — en continu",
    ],
    niveauRequis: "Bac+3 à Bac+5",
    salaireMin: 500000, salaireMax: 2200000,
    avantages: "Boom de la construction urbaine, nombreuses opportunités dans les projets BTP financés par des bailleurs internationaux.",
  },
  {
    nom: 'Architecte',
    domaine: 'btp-energie-industrie', secteur: 'energies-renouvelables-btp-industrie-miniere',
    sousDomaine: 'Architecture & Urbanisme',
    riasecCodes: ['A', 'I', 'R'],
    description: "L'architecte conçoit les plans de bâtiments en alliant esthétique, fonctionnalité et respect des normes, et porte la responsabilité globale du projet architectural.",
    missions: [
      "Concevoir les plans d'un projet (esquisses, avant-projet, plans d'exécution) en fonction des besoins du client et des contraintes du terrain.",
      "Réaliser ou superviser des modélisations 3D et des permis de construire.",
      "Assurer le suivi architectural du chantier et coordonner les différents corps de métier.",
      "Veiller au respect des normes d'urbanisme, de sécurité et d'accessibilité.",
    ],
    competences: ["Créativité", "Capacité à visualiser un espace en trois dimensions", "Culture architecturale"],
    competencesComportementales: ["Maîtrise des normes de construction", "Logiciels de conception (AutoCAD, SketchUp, Revit)"],
    seriesBacMadagascar: ["S"],
    formationsMadagascar: [
      "Supérieur (Diplôme d'architecte) — ESPA - Département Architecture (Antananarivo), écoles privées d'architecture — 5 ans",
      "Spécialisation — Urbanisme, architecture durable — 1 à 2 ans supplémentaires",
      "Inscription à l'Ordre — Ordre des Architectes de Madagascar pour exercer en son nom propre — variable",
    ],
    niveauRequis: "Bac+5 (Diplôme d'architecte)",
    salaireMin: 700000, salaireMax: 3500000,
    avantages: "Forte demande liée à l'urbanisation rapide d'Antananarivo et des grandes villes, métier créatif et valorisant.",
  },
  {
    nom: 'Dessinateur-Projeteur en Bâtiment',
    domaine: 'btp-energie-industrie', secteur: 'energies-renouvelables-btp-industrie-miniere',
    sousDomaine: 'Bâtiment & Construction',
    riasecCodes: ['R', 'A', 'C'],
    description: "Le dessinateur-projeteur traduit les idées de l'architecte ou de l'ingénieur en plans techniques détaillés, prêts à être utilisés sur le chantier.",
    missions: [
      "Réaliser les plans techniques détaillés (façades, coupes, détails de construction) à partir des esquisses de l'architecte.",
      "Utiliser des logiciels de dessin assisté par ordinateur (AutoCAD, Revit) pour produire les documents graphiques du projet.",
      "Calculer les quantités de matériaux nécessaires et préparer les métrés.",
      "Mettre à jour les plans en fonction des modifications demandées en cours de chantier.",
    ],
    competences: ["Sens du détail", "Rigueur dans les calculs et les proportions"],
    competencesComportementales: ["Compréhension des intentions architecturales"],
    seriesBacMadagascar: ["S", "Arts Plastiques"],
    formationsMadagascar: [
      "Supérieur Court (Bac+2/Bac+3) — BTS Bâtiment, formations en dessin technique et logiciels 3D — 2 à 3 ans",
      "Court & Qualifiant — Centres de formation technique en dessin de bâtiment — 6 mois à 1 an",
      "Certification — Certifications logiciels 3D en ligne (AutoCAD, Revit) — en continu",
    ],
    niveauRequis: "Bac+2 à Bac+3",
    salaireMin: 350000, salaireMax: 1500000,
    avantages: "Poste très recherché par les cabinets d'architecture et entreprises de BTP, moins exposé que le chantier.",
  },
  {
    nom: 'Technicien Minier',
    domaine: 'btp-energie-industrie', secteur: 'energies-renouvelables-btp-industrie-miniere',
    sousDomaine: 'Mines & Ressources naturelles',
    riasecCodes: ['R', 'C', 'I'],
    description: "Le technicien minier participe aux opérations d'extraction et de contrôle qualité sur les sites miniers, sous la supervision d'un géologue ou d'un chef de site.",
    missions: [
      "Assister aux relevés géologiques et prélever des échantillons sur le terrain ou en carrière.",
      "Effectuer les analyses de laboratoire de base (granulométrie, teneur) sur les échantillons de minerai.",
      "Participer à la supervision des équipes d'extraction et au respect des consignes de sécurité.",
      "Tenir à jour les registres de production et les rapports journaliers du site.",
    ],
    competences: ["Résistance physique", "Rigueur", "Capacité à travailler en horaires postés"],
    competencesComportementales: ["Sens de l'observation", "Respect strict des normes de sécurité (HSE)"],
    seriesBacMadagascar: ["S"],
    formationsMadagascar: [
      "Court & Qualifiant — Formations sur site par les compagnies minières (Ambatovy, QMM) — 6 mois à 1 an",
      "Supérieur Court (Bac+2/Bac+3) — BTS/DTS en exploitation minière, IST — 2 à 3 ans",
      "Certification — Formations sécurité minière (HSE) — en continu",
    ],
    niveauRequis: "Bac+2 à Bac+3",
    salaireMin: 500000, salaireMax: 1800000,
    avantages: "Salaires attractifs dans les grandes compagnies (Ambatovy, QMM, Kraoma), secteur stratégique pour l'économie nationale.",
  },
  {
    nom: 'Géologue',
    domaine: 'btp-energie-industrie', secteur: 'energies-renouvelables-btp-industrie-miniere',
    sousDomaine: 'Mines, Géologie & Ressources naturelles',
    riasecCodes: ['I', 'R', 'E'],
    description: "Le géologue étudie la composition et la structure du sous-sol pour localiser, évaluer et exploiter durablement les ressources minières de Madagascar (nickel, cobalt, saphir, or, ilménite).",
    missions: [
      "Réaliser des campagnes de prospection géologique et interpréter les données de sondage.",
      "Modéliser les gisements et évaluer les réserves exploitables en lien avec les ingénieurs miniers.",
      "Superviser les études d'impact environnemental et social liées à l'exploitation minière.",
      "Rédiger des rapports techniques pour la direction, les autorités minières ou les investisseurs.",
    ],
    competences: ["Solides bases en géologie, chimie, cartographie et modélisation"],
    competencesComportementales: ["Capacité à diriger des missions de prospection en zones isolées"],
    seriesBacMadagascar: ["S"],
    formationsMadagascar: [
      "Supérieur (Bac+5) — ESPA (Génie Minier), Université d'Antananarivo (Sciences de la Terre) — 5 ans",
      "Spécialisation — Master en géologie minière, gestion environnementale des mines — 1 à 2 ans supplémentaires",
      "Certification — Formations internationales en modélisation de gisements — en continu",
    ],
    niveauRequis: "Bac+5",
    salaireMin: 900000, salaireMax: 4000000,
    avantages: "Salaires parmi les plus élevés du pays, secteur stratégique avec de grands investisseurs internationaux (Ambatovy, QMM).",
  },
  {
    nom: 'Technicien Agricole',
    domaine: 'agriculture-agroindustrie', secteur: 'agro-industrie-elevage-gestion-des-ressources',
    sousDomaine: 'Agriculture & Vulgarisation rurale',
    riasecCodes: ['R', 'I', 'S'],
    description: "Le technicien agricole applique sur le terrain les itinéraires techniques recommandés et accompagne directement les paysans dans les champs, sous la supervision d'un agronome ou d'une coopérative.",
    missions: [
      "Réaliser le suivi technique des parcelles (repiquage, fertilisation, traitement phytosanitaire) chez les producteurs encadrés.",
      "Démontrer et enseigner aux paysans les techniques culturales améliorées (SRI/SRA, compostage).",
      "Collecter les données de terrain (surfaces cultivées, rendements, intrants utilisés) pour les rapports de campagne.",
      "Participer à la distribution de semences, engrais ou petits équipements agricoles dans le cadre de projets de développement.",
    ],
    competences: ["Goût du contact avec les paysans", "Endurance aux déplacements à pied ou à moto", "Sens pratique"],
    competencesComportementales: ["Capacité à repérer une maladie de plante ou une carence du sol", "Rigueur dans la collecte de données"],
    seriesBacMadagascar: ["S", "Technique Agricole", "OSE"],
    formationsMadagascar: [
      "Court & Qualifiant — Centres de formation agricole (CFP agricole, formations pratiques FOFIFA) — 6 à 12 mois",
      "Supérieur Court (Bac+2) — BTS/DTS Agriculture, écoles techniques agricoles régionales — 2 ans",
      "Certification — Stages pratiques via ONG (FERT, CARE, GIZ) — en continu",
    ],
    niveauRequis: "Bac+2",
    salaireMin: 300000, salaireMax: 1000000,
    avantages: "Contact direct et valorisant avec les producteurs, recrutement constant par les ONG et projets de développement rural.",
  },
  {
    nom: 'Ingénieur Agronome',
    domaine: 'agriculture-agroindustrie', secteur: 'agro-industrie-elevage-gestion-des-ressources',
    sousDomaine: 'Agriculture, Agro-industrie & Développement rural',
    riasecCodes: ['I', 'R', 'E'],
    description: "L'ingénieur agronome conçoit les stratégies de production, conduit des études techniques et supervise des programmes agricoles à plus grande échelle, pour des sociétés exportatrices, ministères ou organismes internationaux.",
    missions: [
      "Concevoir et piloter des projets agricoles (irrigation, amélioration variétale, chaînes de valeur export).",
      "Superviser une équipe de techniciens agricoles sur plusieurs zones ou régions.",
      "Réaliser des études de faisabilité, rédiger des rapports stratégiques et présenter les résultats aux bailleurs ou à la direction.",
      "Développer des partenariats avec les coopératives, les instituts de recherche (FOFIFA) et les acheteurs internationaux.",
    ],
    competences: ["Solides bases en agronomie", "Économie agricole", "Gestion de projet"],
    competencesComportementales: ["Capacité à encadrer des équipes multi-sites", "Interagir avec des partenaires institutionnels"],
    seriesBacMadagascar: ["S"],
    formationsMadagascar: [
      "Supérieur (Bac+5) — ESSA (Université d'Antananarivo), universités régionales — 5 ans (Ingéniorat/Master)",
      "Spécialisation — Master en agroéconomie, gestion de l'eau, agro-industrie — 1 à 2 ans supplémentaires",
      "Certification — Formations internationales en gestion de projet agricole (bailleurs) — en continu",
    ],
    niveauRequis: "Bac+5",
    salaireMin: 700000, salaireMax: 3000000,
    avantages: "Poste à responsabilités, forte demande dans les filières d'exportation (vanille, litchi, cacao) et les grands projets internationaux.",
  },
  {
    nom: 'Technicien Agroalimentaire (Transformation & Export)',
    domaine: 'agriculture-agroindustrie', secteur: 'agro-industrie-elevage-gestion-des-ressources',
    sousDomaine: 'Agro-industrie & Transformation alimentaire',
    riasecCodes: ['R', 'I', 'C'],
    description: "Le technicien agroalimentaire supervise la transformation, le contrôle qualité et le conditionnement des produits agricoles destinés à l'export (vanille, litchi, crevette, cacao).",
    missions: [
      "Contrôler la qualité des matières premières à la réception (fraîcheur, taux d'humidité, calibrage).",
      "Superviser les étapes de transformation (séchage, fermentation, conditionnement) selon les normes internationales.",
      "Effectuer des tests qualité en laboratoire (traçabilité, hygiène, conformité sanitaire).",
      "Gérer les stocks et coordonner les équipes de production en période de haute saison.",
    ],
    competences: ["Rigueur", "Sens de l'hygiène", "Capacité à travailler en horaires intensifs pendant les campagnes"],
    competencesComportementales: ["Notions de chimie/biologie appliquée", "Normes qualité (HACCP)"],
    seriesBacMadagascar: ["S"],
    formationsMadagascar: [
      "Court & Qualifiant — Centres de formation agroalimentaire, stages en usine de transformation — 6 mois à 1 an",
      "Supérieur (Bac+3 à Bac+5) — ESSA-IAA (Antananarivo), IST agroalimentaire — 3 à 5 ans",
      "Certification — Formations HACCP, normes export — en continu",
    ],
    niveauRequis: "Bac+3 à Bac+5",
    salaireMin: 400000, salaireMax: 2000000,
    avantages: "Secteur porteur (Madagascar est le 1er exportateur mondial de vanille), forte demande de main-d'œuvre en période de campagne.",
  },
  {
    nom: 'Vétérinaire',
    domaine: 'sante', secteur: 'agro-industrie-elevage-gestion-des-ressources',
    sousDomaine: 'Santé animale & Médecine vétérinaire',
    riasecCodes: ['I', 'S', 'R'],
    description: "Le vétérinaire diagnostique, soigne et prévient les maladies des animaux (bovins, volailles, animaux de compagnie, aquaculture) et garantit la sécurité sanitaire des filières animales.",
    missions: [
      "Diagnostiquer et traiter les maladies animales, réaliser des interventions chirurgicales si nécessaire.",
      "Concevoir et superviser les programmes de vaccination et de prophylaxie des élevages.",
      "Contrôler la qualité sanitaire des produits d'origine animale (viande, lait, œufs, crevettes d'élevage) et délivrer les certificats sanitaires.",
      "Intervenir en urgence lors d'épizooties et coordonner les mesures de biosécurité avec les autorités.",
    ],
    competences: ["Rigueur clinique", "Sang-froid en situation d'urgence", "Bases solides en biologie et pharmacologie animale"],
    competencesComportementales: ["Capacité à conseiller les éleveurs", "Rassurer les propriétaires d'animaux"],
    seriesBacMadagascar: ["S"],
    formationsMadagascar: [
      "Supérieur (Doctorat vétérinaire) — Formation vétérinaire (Antananarivo, universités ou écoles partenaires internationales) — 5 à 6 ans",
      "Spécialisation — Chirurgie animale, santé publique vétérinaire, aquaculture — 1 à 2 ans supplémentaires",
      "Certification — Formations continues en épidémiologie animale — en continu",
    ],
    niveauRequis: "Bac+5/6 (Doctorat vétérinaire)",
    salaireMin: 800000, salaireMax: 3000000,
    avantages: "Profession valorisée, secteur clé pour la sécurité alimentaire, demande croissante liée à l'aquaculture et à l'aviculture industrielle.",
  },
  {
    nom: "Technicien d'Élevage / Zootechnicien",
    domaine: 'agriculture-agroindustrie', secteur: 'agro-industrie-elevage-gestion-des-ressources',
    sousDomaine: 'Élevage & Zootechnie',
    riasecCodes: ['R', 'I', 'S'],
    description: "Le technicien d'élevage accompagne au quotidien les éleveurs pour améliorer l'alimentation, la reproduction et la productivité de leur cheptel, sous la supervision éventuelle d'un vétérinaire.",
    missions: [
      "Conseiller les éleveurs sur l'alimentation, l'habitat et la conduite du cheptel (bovins, volailles, porcins).",
      "Réaliser les soins de base et assister le vétérinaire lors des campagnes de vaccination.",
      "Suivre les performances zootechniques (croissance, reproduction, mortalité) et tenir les registres d'élevage.",
      "Participer à des projets de développement de l'élevage (distribution d'aliments, amélioration génétique).",
    ],
    competences: ["Amour des animaux", "Endurance aux déplacements en zone rurale", "Sens pratique"],
    competencesComportementales: ["Capacité à repérer les signes de maladie ou de sous-nutrition"],
    seriesBacMadagascar: ["S", "Technique Élevage", "OSE"],
    formationsMadagascar: [
      "Court & Qualifiant — CFP élevage, formations FOFIFA/Ministère de l'Élevage — 6 mois à 1 an",
      "Supérieur Court (Bac+2) — BTS/DTS en productions animales — 2 ans",
      "Certification — Formations en aquaculture, aviculture — en continu",
    ],
    niveauRequis: "Bac+2",
    salaireMin: 300000, salaireMax: 1100000,
    avantages: "Secteur clé pour la sécurité alimentaire, forte demande liée au développement de l'aquaculture et de l'aviculture industrielle.",
  },
  {
    nom: 'Agent de Crédit en Microfinance',
    domaine: 'economie-gestion', secteur: 'finance-proximite-microfinance-commerce-distributif',
    sousDomaine: 'Banque, Microfinance, Inclusion financière & Développement rural',
    riasecCodes: ['E', 'C', 'S'],
    description: "L'agent de crédit (ou chargé de portefeuille) fait le pont entre l'institution financière et les micro-entrepreneurs, commerçants ou agriculteurs locaux. Il est sur le terrain pour identifier les besoins de financement et sécuriser les remboursements.",
    missions: [
      "Prospecter de nouveaux clients sur les marchés, dans les boutiques ou les exploitations agricoles.",
      "Évaluer la capacité de remboursement réelle du client (audit des stocks, calcul du chiffre d'affaires journalier, vérification du carnet de vente).",
      "Monter le dossier de demande de prêt et le défendre devant le comité de crédit.",
      "Suivre les échéances de remboursement et effectuer les relances ou démarches de recouvrement amiable en cas d'impayé.",
    ],
    competences: ["Capacité à convaincre", "Créer un climat de confiance rapide", "Détecter les profils fiables"],
    competencesComportementales: ["Aisance avec le calcul mental", "Comptabilité élémentaire"],
    seriesBacMadagascar: ["OSE", "S"],
    formationsMadagascar: [
      "Formation Professionnelle / Accélérée — Modules certifiants en gestion de micro-entreprises, techniques bancaires ou vente — 3 à 6 mois",
      "Supérieur Court (Bac+2) — BTS / DUT en Gestion, Comptabilité, Commerce ou Finance — 2 ans",
      "Licence Professionnelle (Bac+3) — Facultés/instituts habilités MESupReS en Économie, Gestion, Microfinance ou Droit — 3 ans (L3)",
    ],
    niveauRequis: "Bac+2 à Bac+3",
    salaireMin: 450000, salaireMax: 1600000,
    avantages: "Fort volume d'embauches dans toutes les régions (OTIV, BOA, PAMF, ACEP, SIPEM, Baobab, etc.), primes motivantes indexées sur la performance, utilité sociale directe auprès des petits producteurs.",
  },
  {
    nom: 'Comptable',
    domaine: 'economie-gestion', secteur: 'finance-proximite-microfinance-commerce-distributif',
    sousDomaine: 'Finance & Comptabilité',
    riasecCodes: ['C', 'R', 'I'],
    description: "Le comptable enregistre et contrôle au quotidien les opérations financières d'une entreprise ou d'une organisation, garantissant la fiabilité des comptes.",
    missions: [
      "Tenir la comptabilité générale : saisie des écritures, rapprochements bancaires, gestion des factures.",
      "Établir les déclarations fiscales et sociales courantes dans le respect des délais légaux.",
      "Préparer les états financiers périodiques (bilan, compte de résultat) pour la direction.",
      "Assurer le classement et l'archivage des pièces comptables.",
    ],
    competences: ["Sens du détail", "Méthode", "Honnêteté et discrétion"],
    competencesComportementales: ["Bonne maîtrise des chiffres", "Maîtrise d'Excel et de logiciels comptables"],
    seriesBacMadagascar: ["OSE", "S"],
    formationsMadagascar: [
      "Court & Qualifiant — BTS Comptabilité-Gestion, formations logiciels comptables — 2 ans",
      "Supérieur (Bac+3) — INSCAE, Facultés de Gestion — 3 ans (Licence)",
      "Certification — Formations fiscales et logiciels comptables locaux — en continu",
    ],
    niveauRequis: "Bac+2 à Bac+3",
    salaireMin: 400000, salaireMax: 1300000,
    avantages: "Métier recherché dans toutes les entreprises et ONG, base solide pour évoluer vers l'expertise comptable.",
  },
  {
    nom: 'Auditeur / Expert-Comptable',
    domaine: 'economie-gestion', secteur: 'finance-proximite-microfinance-commerce-distributif',
    sousDomaine: 'Finance, Audit & Expertise comptable',
    riasecCodes: ['I', 'C', 'E'],
    description: "L'auditeur ou l'expert-comptable contrôle la fiabilité des comptes d'une organisation et conseille sa direction sur sa gestion financière et sa conformité réglementaire.",
    missions: [
      "Examiner les comptes et les procédures internes d'une entreprise pour vérifier leur conformité et leur fiabilité.",
      "Identifier les risques financiers, fiscaux ou opérationnels et proposer des recommandations.",
      "Certifier les comptes annuels (pour l'expert-comptable) et rédiger des rapports d'audit.",
      "Conseiller la direction sur la stratégie financière, la trésorerie et l'optimisation fiscale.",
    ],
    competences: ["Rigueur", "Sens critique", "Capacité à détecter une anomalie dans un volume important de données"],
    competencesComportementales: ["Capacité à présenter des conclusions parfois délicates à une direction"],
    seriesBacMadagascar: ["OSE", "S"],
    formationsMadagascar: [
      "Supérieur (Bac+5) — INSCAE, Master en Audit et Contrôle de Gestion — 5 ans",
      "Certification professionnelle — Expertise comptable (Ordre des Experts Comptables et Financiers de Madagascar) — plusieurs années après le Master",
      "Perfectionnement — Normes internationales d'audit (ISA), IFRS — en continu",
    ],
    niveauRequis: "Bac+5",
    salaireMin: 600000, salaireMax: 3000000,
    avantages: "Forte valorisation de l'expertise comptable, débouchés dans les grands cabinets internationaux présents à Madagascar.",
  },
  {
    nom: "Infirmier(ère) Diplômé(e) d'État",
    domaine: 'sante', secteur: 'sante-paramedical-action-humanitaire',
    sousDomaine: 'Santé, Soins hospitaliers, Humanitaire & Santé publique',
    riasecCodes: ['S', 'I', 'R'],
    description: "L'infirmier dispense des soins préventifs, curatifs ou palliatifs prescrits par le médecin. Il assure la surveillance constante de l'état clinique des patients et sert de trait d'union fondamental entre le malade, sa famille et l'équipe médicale.",
    missions: [
      "Administrer les traitements prescrits : injections, perfusions, pansements, pose de sondes et prélèvements sanguins.",
      "Surveiller les constantes vitales (tension artérielle, saturation, glycémie, température) et réagir immédiatement aux urgences.",
      "Assurer l'hygiène, le confort physique et l'accompagnement psychologique des malades hospitalisés.",
      "Gérer la traçabilité des dossiers médicaux, les stocks de médicaments du service et la stérilisation du matériel.",
    ],
    competences: ["Capacité d'écoute active", "Patience", "Résistance au stress"],
    competencesComportementales: ["Dextérité manuelle pour les gestes de précision", "Respect strict de l'asepsie"],
    seriesBacMadagascar: ["S", "L"],
    formationsMadagascar: [
      "Secteur Public (Sélectif) — INFAS via concours national officiel — 3 ans (Licence d'État)",
      "Instituts Privés Agréés — Écoles paramédicales privées habilitées par le MESupReS — 3 ans (Diplôme de technicien supérieur / Licence Pro)",
      "Spécialisations (Post-Licence) — Anesthésie-réanimation, bloc opératoire, pédiatrie, santé communautaire — 1 à 2 ans supplémentaires",
    ],
    niveauRequis: "Bac+3 (Licence d'État)",
    salaireMin: 400000, salaireMax: 2500000,
    avantages: "Utilité sociale indiscutable, sentiment direct de sauver des vies, besoin permanent de recrutement (les structures de soins manquent cruellement d'effectifs partout sur l'île).",
  },
  {
    nom: 'Chauffeur-Livreur / Conducteur Poids Lourd',
    domaine: 'transport-logistique', secteur: 'transport-transit-economie-bleue-maritime',
    sousDomaine: 'Transport & Logistique',
    riasecCodes: ['R', 'C', 'E'],
    description: "Le chauffeur professionnel assure le transport de marchandises ou de personnes en toute sécurité, sur de longues distances ou en milieu urbain.",
    missions: [
      "Conduire le véhicule (camion, taxi-brousse, véhicule utilitaire) en respectant le code de la route et les délais de livraison.",
      "Vérifier l'état du véhicule avant le départ (pneus, freins, niveaux) et signaler les anomalies mécaniques.",
      "Charger, arrimer et protéger la marchandise pour éviter tout dommage pendant le trajet.",
      "Gérer les documents de route (bordereaux, carnet de bord) et les formalités aux postes de contrôle.",
    ],
    competences: ["Résistance à la fatigue et aux longs trajets", "Bonne vue", "Réflexes rapides"],
    competencesComportementales: ["Respect strict du code de la route", "Gestion du stress"],
    seriesBacMadagascar: [],
    formationsMadagascar: [
      "Court & Qualifiant — Permis poids lourd + formation transport (auto-écoles professionnelles) — 3 à 6 mois",
      "Perfectionnement — Formations éco-conduite, transport de matières spécifiques — variable",
      "Évolution — Formation en gestion de flotte pour évoluer vers un poste de responsable transport — 6 mois à 1 an",
    ],
    niveauRequis: "Permis poids lourd (Bac non obligatoire)",
    salaireMin: 300000, salaireMax: 1000000,
    avantages: "Demande constante sur tout le territoire, possibilité d'acquérir son propre véhicule à terme.",
  },
  {
    nom: 'Agent de Transit / Déclarant en Douane',
    domaine: 'transport-logistique', secteur: 'transport-transit-economie-bleue-maritime',
    sousDomaine: 'Commerce international & Logistique portuaire',
    riasecCodes: ['C', 'E', 'I'],
    description: "L'agent de transit organise le dédouanement et l'acheminement des marchandises importées ou exportées, en lien avec les douanes et les compagnies maritimes.",
    missions: [
      "Préparer les documents douaniers, factures et déclarations d'import-export selon la réglementation en vigueur.",
      "Calculer les droits et taxes applicables et déposer les dossiers auprès des services douaniers.",
      "Coordonner avec les transporteurs, les compagnies maritimes/aériennes et les clients pour le suivi des marchandises.",
      "Résoudre les blocages administratifs et accélérer le passage des conteneurs au port ou à l'aéroport.",
    ],
    competences: ["Sens du détail", "Connaissance de la réglementation douanière et commerciale"],
    competencesComportementales: ["Capacité à négocier avec les administrations", "Gérer les urgences"],
    seriesBacMadagascar: ["OSE", "S"],
    formationsMadagascar: [
      "Supérieur (Bac+2/Bac+3) — BTS Transport-Logistique, Institut du Commerce International — 2 à 3 ans",
      "Certification — Formation de déclarant en douane agréé — variable",
      "Perfectionnement — Formations en réglementation douanière internationale (COMESA, SADC) — en continu",
    ],
    niveauRequis: "Bac+2 à Bac+3",
    salaireMin: 450000, salaireMax: 2000000,
    avantages: "Secteur essentiel au commerce extérieur (port de Toamasina, zones franches), demande constante.",
  },
  {
    nom: 'Guide Touristique',
    domaine: 'tourisme-hotellerie', secteur: 'tourisme-hotellerie',
    sousDomaine: 'Tourisme, Voyage & Hôtellerie',
    riasecCodes: ['S', 'E', 'A'],
    description: "Le guide touristique accompagne les visiteurs nationaux et étrangers à la découverte des sites naturels et culturels de Madagascar, en garantissant leur sécurité et la qualité de leur expérience.",
    missions: [
      "Concevoir et animer des circuits (parcs nationaux, plages, sites culturels) en assurant la sécurité du groupe.",
      "Traduire, interpréter et transmettre les connaissances naturalistes, historiques et culturelles.",
      "Gérer la logistique du voyage (hébergement, transport, restauration) et le budget du client.",
      "Représenter l'image du pays et gérer la relation client avant, pendant et après le circuit.",
    ],
    competences: ["Aisance relationnelle", "Sens de l'accueil", "Résistance physique"],
    competencesComportementales: ["Culture générale", "Maîtrise de langues étrangères"],
    seriesBacMadagascar: ["L", "S", "OSE"],
    formationsMadagascar: [
      "Court & Qualifiant — Centres de formation touristique (INTH, écoles privées de tourisme) — 6 mois à 1 an",
      "Supérieur (Bac+2/Bac+3) — INTH, universités privées Tourisme — 2 à 3 ans (BTS/Licence Pro)",
      "Certification professionnelle — Carte professionnelle de guide délivrée par le Ministère du Tourisme — variable",
    ],
    niveauRequis: "Bac+2 à Bac+3",
    salaireMin: 300000, salaireMax: 1800000,
    avantages: "Secteur en croissance, contacts internationaux enrichissants, pourboires significatifs en haute saison.",
  },
  {
    nom: "Réceptionniste d'Hôtel",
    domaine: 'tourisme-hotellerie', secteur: 'tourisme-hotellerie',
    sousDomaine: 'Hôtellerie & Tourisme',
    riasecCodes: ['S', 'C', 'E'],
    description: "Le/la réceptionniste est le premier contact du client à son arrivée : il/elle assure l'accueil, les réservations et le bon déroulement du séjour.",
    missions: [
      "Accueillir, renseigner et enregistrer les clients (check-in/check-out) et gérer les réservations.",
      "Répondre aux appels, e-mails et demandes en ligne, en français et en anglais.",
      "Gérer la facturation, les encaissements et transmettre les demandes particulières aux autres services.",
      "Traiter les premières réclamations et orienter vers le service concerné si nécessaire.",
    ],
    competences: ["Sourire et amabilité", "Présentation soignée", "Calme en toute circonstance"],
    competencesComportementales: ["Maîtrise d'un logiciel de réservation", "Rigueur dans la gestion des plannings"],
    seriesBacMadagascar: ["L", "S", "OSE"],
    formationsMadagascar: [
      "Court & Qualifiant — Centres de formation hôtelière, écoles privées — 6 mois à 1 an",
      "Supérieur Court (Bac+2) — BTS Hôtellerie-Restauration — 2 ans",
      "Certification — Stages pratiques en hôtel/resort — en continu",
    ],
    niveauRequis: "Bac+2",
    salaireMin: 300000, salaireMax: 900000,
    avantages: "Premier poste d'entrée très accessible dans le secteur, contacts internationaux enrichissants, logement parfois fourni en resort.",
  },
  {
    nom: "Manager / Directeur d'Hôtel-Restaurant",
    domaine: 'tourisme-hotellerie', secteur: 'tourisme-hotellerie',
    sousDomaine: 'Hôtellerie, Restauration & Tourisme',
    riasecCodes: ['E', 'S', 'C'],
    description: "Le manager ou directeur d'établissement pilote l'ensemble des opérations d'un hôtel ou d'un restaurant : équipes, budget, qualité de service et satisfaction client.",
    missions: [
      "Superviser et coordonner l'ensemble des services (réception, étages, restauration, sécurité).",
      "Élaborer et suivre le budget, les objectifs de chiffre d'affaires et le taux d'occupation.",
      "Recruter, former et manager les équipes ; garantir la qualité du service et la satisfaction client.",
      "Gérer les relations avec les fournisseurs, les agences de voyage et les partenaires commerciaux.",
    ],
    competences: ["Capacité à motiver et fédérer une équipe pluridisciplinaire"],
    competencesComportementales: ["Maîtrise budgétaire", "Indicateurs de performance hôtelière"],
    seriesBacMadagascar: ["OSE"],
    formationsMadagascar: [
      "Supérieur (Bac+3 à Bac+5) — INTH, écoles de management hôtelier — 3 à 5 ans",
      "Évolution interne — Depuis un poste de réceptionniste ou chef de rang, avec expérience — variable",
      "Certification — Formations en gestion hôtelière internationale (revenue management) — en continu",
    ],
    niveauRequis: "Bac+3 à Bac+5",
    salaireMin: 700000, salaireMax: 3000000,
    avantages: "Poste à forte responsabilité et bien rémunéré, secteur touristique en développement, possibilité d'évolution vers la gestion de chaînes hôtelières.",
  },
  {
    nom: "Enseignant(e) du Primaire",
    domaine: 'education-enseignement', secteur: 'education-enseignement',
    sousDomaine: 'Éducation - Enseignement primaire',
    riasecCodes: ['S', 'A', 'C'],
    description: "L'enseignant du primaire accompagne les premiers apprentissages fondamentaux des enfants (lecture, écriture, calcul) et pose les bases de leur scolarité future.",
    missions: [
      "Préparer et animer les cours dans toutes les matières du programme primaire (malgache, français, calcul, éveil).",
      "Adapter la pédagogie aux jeunes enfants et à leurs rythmes d'apprentissage différents.",
      "Évaluer les acquis de base et signaler les difficultés d'apprentissage aux parents.",
      "Instaurer un cadre bienveillant et sécurisant, propice à l'épanouissement de l'enfant.",
    ],
    competences: ["Patience", "Douceur", "Autorité bienveillante"],
    competencesComportementales: ["Capacité à enseigner plusieurs matières différentes"],
    seriesBacMadagascar: ["L", "S", "OSE"],
    formationsMadagascar: [
      "Court & Qualifiant — Formation initiale des maîtres FRAM — 6 mois à 1 an",
      "Supérieur (Bac+3) — ENS, filière Enseignement Primaire, INFP — 3 ans (Licence/CAPEN)",
      "Concours — Concours de la fonction publique enseignante (primaire) — variable",
    ],
    niveauRequis: "Bac+3 (Licence/CAPEN)",
    salaireMin: 180000, salaireMax: 800000,
    avantages: "Stabilité de l'emploi public, vacances scolaires, rôle fondateur dans l'éducation des enfants.",
  },
  {
    nom: "Enseignant(e) du Secondaire",
    domaine: 'education-enseignement', secteur: 'education-enseignement',
    sousDomaine: 'Éducation - Enseignement secondaire',
    riasecCodes: ['S', 'I', 'A'],
    description: "L'enseignant du secondaire transmet une discipline spécifique (mathématiques, sciences, lettres, langues...) à des collégiens et lycéens, en les préparant aux examens officiels.",
    missions: [
      "Préparer et animer des cours approfondis dans une discipline précise selon les programmes officiels.",
      "Évaluer les acquis des élèves et préparer les classes aux examens (BEPC, Baccalauréat).",
      "Gérer la dynamique de classe avec des adolescents et maintenir la discipline.",
      "Participer aux conseils de classe et au suivi de l'orientation des élèves.",
    ],
    competences: ["Très bonne connaissance de la matière enseignée", "Capacité à approfondir un sujet"],
    competencesComportementales: ["Autorité affirmée face à un public adolescent", "Capacité à capter l'attention"],
    seriesBacMadagascar: ["S", "L", "OSE"],
    formationsMadagascar: [
      "Court & Qualifiant — Contrats de formation du Ministère pour enseignants contractuels — 6 mois à 1 an",
      "Supérieur (Bac+4) — ENS (Antananarivo), Universités (Lettres, Sciences) — 4 ans (Licence/CAPEN)",
      "Concours — Concours de la fonction publique enseignante (secondaire) — variable",
    ],
    niveauRequis: "Bac+4 (Licence/CAPEN)",
    salaireMin: 220000, salaireMax: 1100000,
    avantages: "Stabilité de l'emploi public, possibilité de revenus complémentaires via les cours particuliers très demandés (matières scientifiques notamment).",
  },
  {
    nom: "Juriste d'Entreprise",
    domaine: 'droit-sciences-politiques', secteur: 'autres-secteurs-porteurs',
    sousDomaine: 'Droit, Justice & Conseil juridique',
    riasecCodes: ['C', 'I', 'E'],
    description: "Le juriste d'entreprise conseille et sécurise juridiquement les activités d'une société, d'une ONG ou d'une administration, sans nécessairement plaider devant les tribunaux.",
    missions: [
      "Rédiger et analyser les contrats, statuts et actes juridiques de l'entreprise.",
      "Conseiller la direction sur les risques juridiques liés à l'activité (droit du travail, droit des affaires, droit foncier).",
      "Assurer la veille réglementaire et la mise en conformité de l'entreprise.",
      "Gérer les litiges à l'amiable et coordonner avec les avocats externes si nécessaire.",
    ],
    competences: ["Rigueur analytique", "Capacité rédactionnelle", "Sens de la synthèse"],
    competencesComportementales: ["Capacité à traduire un texte de loi en recommandation opérationnelle claire"],
    seriesBacMadagascar: ["L", "S", "OSE"],
    formationsMadagascar: [
      "Supérieur (Licence à Master) — Facultés de Droit — 4 à 5 ans (Master)",
      "Spécialisation — Master en droit des affaires, droit fiscal ou droit foncier — 1 à 2 ans supplémentaires",
      "Certification — Formations en droit OHADA, conformité — en continu",
    ],
    niveauRequis: "Bac+4 à Bac+5 (Master)",
    salaireMin: 500000, salaireMax: 2500000,
    avantages: "Poste stable dans les entreprises, banques et ONG, forte demande en droit des affaires et droit foncier.",
  },
  {
    nom: 'Avocat',
    domaine: 'droit-sciences-politiques', secteur: 'autres-secteurs-porteurs',
    sousDomaine: 'Droit, Justice & Barreau',
    riasecCodes: ['E', 'I', 'A'],
    description: "L'avocat représente et défend les intérêts de ses clients devant les tribunaux et les conseille sur toutes questions juridiques, en exercice libéral ou en cabinet.",
    missions: [
      "Étudier les dossiers, construire une stratégie de défense ou d'accusation et rechercher la jurisprudence pertinente.",
      "Rédiger les actes de procédure (assignations, conclusions, plaintes) et plaider devant les tribunaux.",
      "Conseiller les clients (particuliers ou entreprises) sur leurs droits et les risques judiciaires.",
      "Négocier des accords amiables pour éviter ou clore un contentieux.",
    ],
    competences: ["Sens de l'argumentation", "Aisance à l'oral", "Charisme et conviction"],
    competencesComportementales: ["Rigueur analytique", "Mémorisation de textes", "Résistance à la pression du prétoire"],
    seriesBacMadagascar: ["L", "S", "OSE"],
    formationsMadagascar: [
      "Supérieur (Licence à Master) — Facultés de Droit — 4 ans minimum (Maîtrise)",
      "Professionnalisation — CAPA, après le Barreau — 1 à 2 ans",
      "Spécialisation — Master en droit pénal, droit des affaires ou droit foncier — 1 à 2 ans supplémentaires",
    ],
    niveauRequis: "Bac+4 (Maîtrise) + CAPA",
    salaireMin: 500000, salaireMax: 4000000,
    avantages: "Profession valorisée socialement, possibilité d'ouvrir son propre cabinet, forte demande en droit des affaires et droit foncier.",
  },
  {
    nom: 'Brodeur-Couturier / Artisan Textile d\'Export',
    domaine: 'arts-communication', secteur: 'autres-secteurs-porteurs',
    sousDomaine: "Artisanat, Textile & Industrie d'exportation",
    riasecCodes: ['R', 'A', 'E'],
    description: "L'artisan textile transforme des matières premières locales (raphia, soie sauvage, coton) en produits artisanaux ou en pièces textiles destinées au marché local et à l'export.",
    missions: [
      "Concevoir des modèles ou motifs originaux (broderie, tissage, maroquinerie) selon les tendances demandées.",
      "Couper, coudre, broder ou tisser les pièces avec précision et finition soignée.",
      "Contrôler la qualité et respecter les cahiers des charges des acheteurs (zones franches, coopératives export).",
      "Gérer les stocks de matières premières et les délais de production.",
    ],
    competences: ["Dextérité manuelle", "Sens esthétique", "Patience et minutie"],
    competencesComportementales: ["Créativité", "Capacité à suivre des consignes techniques précises"],
    seriesBacMadagascar: ["OSE", "L"],
    formationsMadagascar: [
      "Court & Qualifiant — Centres de formation professionnelle artisanale (CFP, coopératives, ONG type Fanamby) — 3 à 6 mois",
      "Supérieur (pour évoluer) — Écoles de mode et stylisme privées (Antananarivo) — 2 à 3 ans (styliste / chef d'atelier)",
      "Apprentissage — Transmission familiale ou en atelier — variable",
    ],
    niveauRequis: "Niveau collège (Bac non obligatoire)",
    salaireMin: 250000, salaireMax: 900000,
    avantages: "Le secteur textile est l'un des premiers employeurs formels du pays ; le savoir-faire malgache (broderie, raphia) est reconnu à l'international.",
  },
  {
    nom: 'Agent de Sécurité Privée',
    domaine: 'securite-defense', secteur: 'autres-secteurs-porteurs',
    sousDomaine: 'Sécurité privée',
    riasecCodes: ['R', 'C', 'S'],
    description: "L'agent de sécurité privée assure la protection des biens et des personnes pour le compte d'entreprises, banques, résidences ou chantiers.",
    missions: [
      "Surveiller un site et contrôler les accès des personnes et véhicules.",
      "Effectuer des rondes de surveillance et vérifier le bon fonctionnement des équipements de sécurité (alarmes, caméras).",
      "Intervenir en cas d'incident, alerter les forces de l'ordre et rédiger des rapports d'incident.",
      "Appliquer les consignes de sécurité incendie et les procédures d'urgence du site.",
    ],
    competences: ["Vigilance", "Sang-froid", "Bonne condition physique"],
    competencesComportementales: ["Respect strict des consignes et des procédures"],
    seriesBacMadagascar: [],
    formationsMadagascar: [
      "Court & Qualifiant — Centres de formation en sécurité privée agréés — 3 à 6 mois",
      "Certification — Formations spécialisées (secourisme, sécurité incendie, protection rapprochée) — en continu",
      "Évolution — Formation de chef de poste / superviseur de sécurité avec expérience — quelques mois supplémentaires",
    ],
    niveauRequis: "Niveau BEPC/collège",
    salaireMin: 250000, salaireMax: 800000,
    avantages: "Forte demande dans les entreprises, banques et résidences, embauche rapide.",
  },
  {
    nom: 'Policier / Gendarme',
    domaine: 'securite-defense', secteur: 'autres-secteurs-porteurs',
    sousDomaine: 'Défense, Ordre public & Sécurité nationale',
    riasecCodes: ['R', 'S', 'C'],
    description: "Le policier ou le gendarme assure le maintien de l'ordre public, la protection des citoyens et l'application des lois sur l'ensemble du territoire malgache.",
    missions: [
      "Assurer des patrouilles et le maintien de l'ordre public dans une zone donnée.",
      "Intervenir lors d'infractions, effectuer des contrôles et rédiger des procès-verbaux.",
      "Mener des enquêtes judiciaires en lien avec le parquet et les autorités compétentes.",
      "Participer aux opérations de sécurisation lors d'événements publics ou de situations de crise.",
    ],
    competences: ["Discipline stricte", "Courage", "Sens du devoir et de l'autorité"],
    competencesComportementales: ["Capacité à travailler en hiérarchie", "Obéir aux ordres tout en faisant preuve de discernement"],
    seriesBacMadagascar: ["L", "S", "OSE"],
    formationsMadagascar: [
      "Concours national — École Nationale de Police, École de la Gendarmerie — 1 à 2 ans de formation initiale",
      "Carrière d'officier — Concours d'entrée aux écoles d'officiers (police ou gendarmerie) — 2 à 4 ans",
      "Spécialisation — Formations en police judiciaire, maintien de l'ordre, unités spécialisées — en continu",
    ],
    niveauRequis: "Bac (admis au concours)",
    salaireMin: 350000, salaireMax: 1200000,
    avantages: "Emploi stable de la fonction publique, sens du service à la nation, possibilité d'évolution de carrière par concours interne.",
  },
  {
    nom: 'Chargé(e) des Ressources Humaines',
    domaine: 'economie-gestion', secteur: 'autres-secteurs-porteurs',
    sousDomaine: 'Ressources Humaines & Administration du personnel',
    riasecCodes: ['S', 'E', 'C'],
    description: "Le chargé des ressources humaines gère le recrutement, la formation et l'administration du personnel d'une entreprise.",
    missions: [
      "Recruter, sélectionner et intégrer les nouveaux collaborateurs selon les besoins de l'entreprise.",
      "Gérer les contrats de travail, la paie, les congés et les dossiers administratifs du personnel (CNaPS, OSTIE).",
      "Organiser les formations et accompagner le développement des compétences des employés.",
      "Gérer les relations sociales et prévenir ou résoudre les conflits internes.",
    ],
    competences: ["Écoute", "Diplomatie", "Sens de la confidentialité"],
    competencesComportementales: ["Rigueur administrative", "Connaissance du droit du travail malgache"],
    seriesBacMadagascar: ["OSE", "L", "S"],
    formationsMadagascar: [
      "Court & Qualifiant — BTS Gestion des Ressources Humaines — 2 ans",
      "Supérieur (Bac+3 à Bac+5) — INSCAE, Facultés de Droit/Gestion (Master RH) — 3 à 5 ans",
      "Certification — Formations en droit du travail et en gestion de la paie — en continu",
    ],
    niveauRequis: "Bac+2 à Bac+5",
    salaireMin: 400000, salaireMax: 2200000,
    avantages: "Fonction transversale présente dans toutes les entreprises et ONG, rôle clé dans le climat social de l'organisation.",
  },
];

async function uniqueSlug(nom: string) {
  const base = slugify(nom);
  let slug = base;
  let i = 1;
  while (await prisma.metier.findUnique({ where: { slug } })) {
    slug = `${base}-${i++}`;
  }
  return slug;
}

async function main() {
  const domaines = new Map<string, string>();
  const secteurs = new Map<string, string>();

  for (const d of await prisma.domaine.findMany()) domaines.set(d.slug, d.id);
  for (const s of await prisma.secteur.findMany()) secteurs.set(s.slug, s.id);

  for (const m of metiersData) {
    const domaineId = domaines.get(m.domaine);
    const secteurId = secteurs.get(m.secteur);
    if (!domaineId) throw new Error(`Domaine introuvable: ${m.domaine}`);
    if (!secteurId) throw new Error(`Secteur introuvable: ${m.secteur}`);

    const existing = await prisma.metier.findFirst({ where: { nom: m.nom, domaineId } });
    const data = {
      domaineId,
      secteurId,
      sousDomaine: m.sousDomaine,
      riasecCodes: m.riasecCodes,
      description: m.description,
      missions: m.missions,
      competences: m.competences,
      competencesComportementales: m.competencesComportementales,
      seriesBacMadagascar: m.seriesBacMadagascar,
      formationsMadagascar: m.formationsMadagascar,
      niveauRequis: m.niveauRequis,
      salaireMin: m.salaireMin,
      salaireMax: m.salaireMax,
      avantages: m.avantages,
      sources: ['Guide des Fiches Métiers à Madagascar — Avenir assuré'],
    };

    if (existing) {
      await prisma.metier.update({ where: { id: existing.id }, data });
      console.log(`MAJ: ${m.nom}`);
    } else {
      const slug = await uniqueSlug(m.nom);
      await prisma.metier.create({ data: { ...data, nom: m.nom, slug } });
      console.log(`Créé: ${m.nom}`);
    }
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
